# Kamal 2 deploy config — https://kamal-deploy.org
service: shopzilla
image: chrisbaptiste83/shopzilla

servers:
  web:
    hosts:
      - 172.235.34.185

proxy:
  ssl: true
  host: gloriasembroideryshop.com

registry:
  username: chrisbaptiste83
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    RAILS_ENV: production
    SOLID_QUEUE_IN_PUMA: true
    STRIPE_PUBLISHABLE_KEY: pk_live_51RpoJNRvD8xPSLFB5jDzQn6LOleyWHoc3ehv2h8ArfVZAIdG4sjBnS2DVfz7q9f49R9u1m4OB1gwlr9rfYSjhvdP00nV9YXhS4
    FRONTEND_URL: https://chrisbaptiste83.github.io
  secret:
    - RAILS_MASTER_KEY
    - STRIPE_SECRET_KEY

volumes:
  - shopzilla_storage:/rails/storage

asset_path: /rails/public/assets
